# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 405)
        MainWindow.setMinimumSize(QtCore.QSize(300, 405))
        MainWindow.setMaximumSize(QtCore.QSize(300, 405))
        MainWindow.setStyleSheet("background-image: url(:/image/background.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTxt.setGeometry(QtCore.QRect(40, 40, 221, 20))
        self.inputTxt.setStyleSheet("background-image: url(:/image/Whitescreen.png);")
        self.inputTxt.setObjectName("inputTxt")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(100, 70, 92, 35))
        self.btnCalculate.setStyleSheet("background-image: url(:/image/button.png);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btnCalculate.setObjectName("btnCalculate")
        self.displayText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displayText.setGeometry(QtCore.QRect(40, 120, 221, 241))
        self.displayText.setStyleSheet("background-image: url(:/image/Whitescreen.png);")
        self.displayText.setObjectName("displayText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.btnCalculate.clicked.connect(self.calculate)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "โปรแกรมแม่สูตรคูณ"))
        self.btnCalculate.setText(_translate("MainWindow", "คำนวณ"))

    def calculate(self):
        result=self.inputTxt.text()
        self.displayText.setPlainText("")
        #self.inputTxt.setText("")
        for i in range(1,13):
            cal=int(result)*i
            self.displayText.appendPlainText(result+"x"+str(i)+"="+str(cal))


import MyImage_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
