# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyFoodDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 425)
        MainWindow.setMinimumSize(QtCore.QSize(435, 425))
        MainWindow.setMaximumSize(QtCore.QSize(435, 425))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btncalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btncalculate.setGeometry(QtCore.QRect(180, 170, 75, 23))
        self.btncalculate.setObjectName("btncalculate")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 20, 171, 31))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.displayText = QtWidgets.QLabel(self.centralwidget)
        self.displayText.setGeometry(QtCore.QRect(230, 240, 161, 21))
        self.displayText.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.displayText.setObjectName("displayText")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 60, 351, 101))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.foodmenu = QtWidgets.QComboBox(self.widget)
        self.foodmenu.setObjectName("foodmenu")
        self.foodmenu.addItem("")
        self.foodmenu.addItem("")
        self.foodmenu.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.foodmenu)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.quantity = QtWidgets.QComboBox(self.widget)
        self.quantity.setObjectName("quantity")
        self.quantity.addItem("")
        self.quantity.addItem("")
        self.quantity.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quantity)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.delivery = QtWidgets.QComboBox(self.widget)
        self.delivery.setObjectName("delivery")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.delivery)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "โปรแกรมร้านอาหาร"))
        self.btncalculate.setText(_translate("MainWindow", "คำนวณ"))
        self.label_4.setText(_translate("MainWindow", "โปรแกรมจัดส่งอาหาร"))
        self.displayText.setText(_translate("MainWindow", "ยอดชำระเงิน 0.00 บาท"))
        self.label.setText(_translate("MainWindow", "เมนู"))
        self.foodmenu.setItemText(0, _translate("MainWindow", "คะน้าหมูกรอบ / 50"))
        self.foodmenu.setItemText(1, _translate("MainWindow", "ต้มยำกุ้ง / 100"))
        self.foodmenu.setItemText(2, _translate("MainWindow", "กะเพราหมูกรอบ / 40"))
        self.label_2.setText(_translate("MainWindow", "จำนวน"))
        self.quantity.setItemText(0, _translate("MainWindow", "1"))
        self.quantity.setItemText(1, _translate("MainWindow", "2"))
        self.quantity.setItemText(2, _translate("MainWindow", "3"))
        self.label_3.setText(_translate("MainWindow", "ค่าจัดส่ง"))
        self.delivery.setItemText(0, _translate("MainWindow", "20"))
        self.delivery.setItemText(1, _translate("MainWindow", "30"))
        self.delivery.setItemText(2, _translate("MainWindow", "40"))
        self.delivery.setItemText(3, _translate("MainWindow", "50"))
        self.btncalculate.clicked.connect(self.calculate)
        self.foodmenu.currentTextChanged.connect(self.calculate)
        self.quantity.currentTextChanged.connect(self.calculate)
        self.delivery.currentTextChanged.connect(self.calculate)

    def calculate(self):
        price=int(self.foodmenu.currentText().split("/")[1].strip())
        foodquantity=int(self.quantity.currentText())
        delivery=int(self.delivery.currentText())
        total=price*foodquantity+delivery
        self.displayText.setText("ยอดชำระเงิน "+str(total)+" บาท")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
